export { BestSellingSection } from './sections/BestSellingSection'
export { CategoriesSection } from './sections/CategoriesSection'
export { EssentialsSection } from './sections/EssentialsSection'
export { HeadImageSection } from './sections/HeadImageSection'
export { NewArrivalsSection } from './sections/NewArrivalsSection'
export { WantToSellSection } from './sections/WantToSellSection'
export { InfoSection } from './sections/InfoSection'
